apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app.kubernetes.io/name: web
  type: NodePort
  ports:
  - name: http-backend
    port: 8081
    targetPort: http-backend
    protocol: TCP
    appProtocol: HTTP